Add toggle for PSP and fix security warnings
giantswarm/cluster-api-app pull request #182
Opened 2024-01-18 10:08 UTC by erkanerol

2024-01-18 11:07 UTC, weseven approved these changes

2024-01-18 12:11 UTC, Gacko requested changes

2024-01-18 12:11 UTC, Gacko commented on config/helm/patches/deployments/capi-controller-manager.yaml
> +            type: RuntimeDefault
Have you seen this is being deleted a few lines above? Why not just drop the `$patch: delete`? :)

2024-01-18 12:11 UTC, Gacko commented on helm/cluster-api/templates/crd-install/crd-job.yaml
> +            type: RuntimeDefault
This should be set either on pod or on container level, but it doesn't need to be set on the both of them.

2024-01-18 12:11 UTC, Gacko commented on helm/cluster-api/templates/hook-delete-aggregated-roles/job.yaml
> +          type: RuntimeDefault
Same here. Either container or pod, not both.

2024-01-18 12:12 UTC, Gacko requested changes

2024-01-18 12:12 UTC, Gacko commented on helm/cluster-api/templates/crd-install/crd-psp.yaml
> +{{- if not .Values.global.podSecurityStandards.enforced }}
Please also incorporate this condition in the according role and role binding.

2024-01-18 12:46 UTC, Gacko commented
Also adding seccomp profile requires adding an annotation to the existing PSP. I'll check if we need that PSP at all.

2024-01-18 13:28 UTC, erkanerol commented
> Hope it's fine with you that I just implemented my thoughts and improvements in this PR.

NO. WHY DON'T YOU TOUCH MY PR WITHOUT GETTING MY APPROVAL???????


just kidding :D  I am OK. Please tell me when you are done and let me verify the last version in CAPZ side.

2024-01-18 13:37 UTC, erkanerol commented
> Also adding seccomp profile requires adding an annotation to the existing PSP. I'll check if we need that PSP at all.

I haven't hit any issues regarding this on the CAPI side.

2024-01-19 18:59 UTC, Gacko approved these changes

2024-01-19 19:02 UTC, merged