Enable ignition feature gate
giantswarm/cluster-api-app pull request #84
Opened 2022-07-20 18:29 UTC by kopiczko

2022-07-21 07:04 UTC, glitchcrab approved these changes

2022-07-21 07:44 UTC, fiunchinho commented
Wouldn't this enable ignition for all clusters? According to [upstream docs](https://main.cluster-api.sigs.k8s.io/tasks/experimental-features/ignition.html#supported-infrastructure-providers) ignition is only supported on `aws`

2022-07-21 09:08 UTC, kopiczko commented
> Wouldn't this enable ignition for all clusters? According to [upstream docs](https://main.cluster-api.sigs.k8s.io/tasks/experimental-features/ignition.html#supported-infrastructure-providers) ignition is only supported on `aws`

It does, but do you see a problem with that? If you don't set `format: ignition` in your CRs it doesn't change a thing. If that will make feel you more comfortable I can set a flat for this. LMK.

2022-07-21 09:23 UTC, fiunchinho commented
If it's enabled changing the CR's, then it's fine.

2022-07-21 09:23 UTC, fiunchinho requested changes
The helm chart is generated using `kustomize`. It seems you only changed the output, but you need to change what's inside the `config` folder.

2022-07-22 16:02 UTC, kopiczko commented
@fiunchinho I added the changes to the ./config and ran `make generate`.

2022-07-25 05:32 UTC, bavarianbidi approved these changes

2022-07-25 12:56 UTC, nprokopic approved these changes

2022-07-27 10:26 UTC, fiunchinho approved these changes

2022-07-27 10:26 UTC, merged